#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# ***
# $ pre-push hook to stop code that
# 1. fails linting
# 2. fails build  
# ***

# Linting
npm run lint

# Build
npm run build

# *** Testing will be done in the CI pipeline (GitHub Actions) *** #